### ISSUE TITLE
Consistent field names in reports

### ISSUE THREAD

**Issue by Zweitze** [googleads/google-ads-dotnet#12]
The most hated 'feature' in previous AdWords API was the inconsistency in field names in reports. For instance, if you request field _CreativeQualityScore_ then the resulting report would have a field named _adRelevance_.
This sounds like a one-time nuisance, but when the API version got upgraded, and the upgrade docs stated for instance that _CpcBid_ may now give a "--" result, then you had to go through your sources to look for _maxCPC_. And if a field was discontinued, you had to look in OLDER documentation what its result name would be. And so on.

Unfortunately Ads API seems to have the same problem. You ask for _ad_group.name_, and you get _AdGroup.Name_. Can't we use the exact same names? And also the same usage of uppercase and lowercase.

Note: Maybe it's not a problem in the library, but a problem in the API. In that case, can this bug be passed on?

**Comment by AnashOommen** [comment]
Hi Zwitze,

This one is unfortunately a problem on the client library side itself, but one that is unlikely to get fixed. There are two parts to this issue.

1. In the Google Ads API, you can retrieve a field name by specifying its path in the class structure, as shown in the [documentation](https://developers.google.com/google-ads/api/docs/fields/campaign#campaigndynamic_search_ads_setting) or the [proto buffer definition](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v0/resources/campaign.proto#L104)

e.g. To retrieve the domain_name field in the dynamic_search_ads_setting field of the campaign entity, you need to request `campaign.dynamic_search_ads_setting.domain_name` in your selector field. This same logic extends to reporting also.

E.g. in the [GetKeywordStats code example](https://github.com/googleads/google-ads-dotnet/blob/master/examples/Services/Reporting/GetKeywordStats.cs#L62), we request `metrics.cost_micros` field because the entity `Metrics` [has a field by that name](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v0/common/metrics.proto#L111).

So in that sense, there's no more discrepancy in terms of selector name and column name. You get what you request. This should also address the magic values like "--". Since cost_micros is an Int64Value in proto buffer definition (which is mapped to a long? on the client library side), you either get a null, or an actual value in the reporting results.

2. As far as field names in the client libraries go, they are generated from the proto buffer definitions, in a way that matches the language's common naming conventions. C# uses PascalCase to match with [Microsoft's conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions), where as protocol buffer fields are snake_cased. The code generator does the snake=>pascal conversion by capitalizing every letter after the underscore. 

So, `campaign.dynamic_search_ads_setting.domain_name` in protocol buffer definition maps to `DynamicSearchAdsSetting.DomainName` property of a Campaign object.

This convention is baked into all the other Google APIs, and it is unlikely that we can break it. It will also make the external developers unhappy.

That still leaves the issue you raised, so I'm thinking of generating [enums like in the existing client library](https://github.com/googleads/googleads-dotnet-lib/blob/master/examples/AdWords/CSharp/v201806/BasicOperations/GetCampaigns.cs#L63) so the end user won't have to worry about the naming style differences.

Pls chime in your thoughts.

**Comment by Zweitze** [comment]
If you consider generating different enums, do realize that you also have to update the documentation on Ads API. I don't think this will happen as other libraries may use the naming as seen in the current docs.

My point is that Ads API should use consistent naming AND use the same naming as used in its documentation.
Consistency with naming conventions of other parties is by far not as important.

You stated all Google libraries follow the same naming conventions.
I don't think this is the case, not all Google API libraries apply naming conventions of a language. For instance, recently I did a project in Python using Google DBM API - and note that Python is probably more strict on naming conventions, and tries to enforce snake_casing. Now, Python library oauth2client has a method "GoogleCredentials", doubleclickbidmanager service has a method "lineitems", etc. Those libraries have no problem leaving preferred Python naming conventions.

However, I do realize that sometimes naming conflicts can occur. In such cases I like the approach of existing AdWords API, in class Predicate. The API states this has a member "operator", but that exact name cannot be used in C# classes. So, in the library this member was renamed to "@operator". I like this workaround.

**Comment by AnashOommen** [comment]
I did explore this further, however we decided to stick with the current naming style which is consistent with other Google GRPC APIs.
