### ISSUE TITLE
Can not install 'Google.Ads.GoogleAds v5.0.0' with Nuget Package Management

### ISSUE THREAD

**Issue by hojun920** [googleads/google-ads-dotnet#245]
**Which version of the client library are you using?**
 - Google.Ads.GoogleAds v5.0.0

**Which version of .NET are you using?**
 - .NET Framework 4.7.2

**Which operating system (Linux, Windows, ...) and version?**
 - Windows 10 Pro (x64), Visual Studio 2015 version 14.0 Update 3

When installing with Nuget Package Management, the following error message is displayed.

```
Could not install package 'Microsoft.Extensions.Configuration 3.1.7'. You are trying to install this package into a project that targets
 '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that 
are compatible with that framework. For more information, contact the package author
```

'Google.Ads.GoogleAds v5.0.0' cannot be installed because of 'Microsoft.Extensions.Configuration'.

How to solve this problem?

**Comment by AnashOommen** [comment]
I think this has to do with Visual Studio 2015, rather than .NET SDK 4.7.2. This is what Visual Studio 2019 generates for me, when creating a Console Application for .NET SDK 472 and adding Nuget reference to Google.Ads.GoogleAds, 5.0.0.

[TestDeps.zip](https://github.com/googleads/google-ads-dotnet/files/5356615/TestDeps.zip)

Could you try this with Visual Studio Community Edition or just compare the two csprojs to see what differs?

**Comment by hojun920** [comment]
Thank you @AnashOommen 

solved in visual studio 2019
