### ISSUE TITLE
Not-in filter excludes too many results

### ISSUE THREAD

**Issue by momolasd** [googleads/google-ads-dotnet#250]
**Which version of the client library are you using?**
6.0.0

**Which version of .NET are you using?**
.Net Standard 2.1

**Which operating system (Linux, Windows, ...) and version?**
Windows

**Actions taken**
string query = $@"SELECT
                                campaign.id,
                                campaign.name,
                                campaign.serving_status,
                                campaign.status,
                                campaign.advertising_channel_type,
                                campaign.advertising_channel_sub_type,
                                metrics.absolute_top_impression_percentage,
                                metrics.average_cpc,
                                metrics.clicks,
                                metrics.conversions,
                                metrics.conversions_value,
                                metrics.cost_micros,
                                metrics.cost_per_conversion,
                                metrics.ctr,
                                metrics.impressions,
                                metrics.top_impression_percentage
                            FROM
	                            campaign
                            WHERE campaign.advertising_channel_sub_type NOT IN ('DISPLAY_EXPRESS', 'SEARCH_EXPRESS')";

**Expected result**
A list of campaigns whose advertising channel type is not display_express and is not search_express

**Actual result**

A list of campaigns whose advertising channel type is neither display_express, nor search_express nor unspecified
From what I understand, the "not in" also filters the campaigns that do not have an advertising channel sub type

**Comment by AnashOommen** [comment]
Hi Moerland,

This seems an issue with the underlying API. Could you please drop an email to googleadsapi-support@google.com with the following details?

1. The customer ID for which you saw the incorrect behaviour.
2. The API call logs. Instructions to turn on logging is here: https://developers.google.com/google-ads/api/docs/client-libs/dotnet/logging.
3. Specific campaign IDs / names you were expecting to see in the response, but didn't.

Feel free to add Attn: Anash to the email and reference this issue. 

I'll close this issue here for now.
