### ISSUE TITLE
Support all available ChangeEventResourceType values

### ISSUE THREAD

**Issue by FilipFilipov** [googleads/google-ads-dotnet#263]
It seems not all the [ChangeEventResourceType](https://developers.google.com/google-ads/api/reference/rpc/v6/ChangeEventResourceTypeEnum.ChangeEventResourceType) values available from the API are currently supported by the library

Specifically it is missing:
- FEED
- FEED_ITEM
- CAMPAIGN_FEED
- AD_GROUP_FEED
- AD_GROUP_AD

Adding them to the examples would be helpful as well

**Comment by AnashOommen** [comment]
That's because the v6_1 API release was yesterday evening -- a couple of hours before you opened the bug. The updated client libraries will be available in all languages by next week, likely earlier.

**Comment by FilipFilipov** [comment]
Okay, I only started using the API a few days ago, so I didn't realize it was updated. Also the NuGet package was already at 6.1.0, so that's a bit confusing.

**Comment by AnashOommen** [comment]
The library and API version numbers don't go in sync because we need to sunset old API versions occasionally, and since that's a breaking change, we need a major version bump. In general, you should ignore the client library version. Always look at the API documentation to determine which API version to use.

**Comment by AnashOommen** [comment]
This is fixed in v7.0.0 of the library.
