### ISSUE TITLE
Correct Version # to correspond with Google Ads API

### ISSUE THREAD

**Issue by ToddEvansHome** [googleads/google-ads-dotnet#298]
**Describe the problem you are trying to solve**
The version # being used to document the nuget changes is out of sync with Google Ads API.
Currently this Nuget package is version 8, but the code is actually referencing Google.Ads.GoogleAds.V7 namespace.

New users will assume the Nuget version(which is currently 8) will work with and have the features of Google Ads API version 8.

**Describe the solution you would like**
Nuget version should correspond with Google Ad API version to avoid confusion.

**Describe alternatives you've considered**
Review the source code to verify which Google Ads API version

**Additional context**
Version #'s are some what arbitrary, but this change will help new users, or even current ones.

**Comment by AnashOommen** [comment]
@ToddEvansHome it is not feasible to fix this issue right now, since the various versions of the API do not launch and sunset in perfect sync. One way to fix this would be to decouple the stubs and the rest of the code, so that the version of the stubs and the API version can then stay in sync. But this introduces other complications as users upgrade from one version to the next, so this isn't an architectural change we are planning to pursue right now.
