### ISSUE TITLE
Google Ads Client Library V5 suddenly stopped working

### ISSUE THREAD

**Issue by MarcoRoberti1995** [googleads/google-ads-dotnet#302]
Hi

we have experienced some issues with the Google Ads API and I have outlined it below:

Google Client Library Version:                                                V5
Sunset Date:                                                                               23/06/2021
Stopped Working Date:                                                            20/07/2021
Challenges:                                                                                 We were assured by Google that the libraries would continue to work post sunset date but then they suddenly stopped working and throwing the error highlighted below when making the requests to the APIs
Notes:                                                                                          Initially installed the V5 version because of compatibility issues with Microsoft Libraries. Newer version were referencing Microsoft.Abstraction.Configuration and Microsoft.Abstraction.Logging 5.0.0 which are not compatible with .Net Core 3.1
Error:                                                                                                     (StatusCode="InvalidArgument", Detail="Request contains an invalid argument.", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1626801031.762000000","description":"Error received from peer 
ipv4:74.125.193.95:443","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\surface\call.cc","file_line":1062,"grpc_message":"Request contains an invalid argument.","grpc_status":3}")
When calling the following services:
•	Services.V5.ConversionAdjustmentUploadService;
•	Services.V5.ConversionUploadService;

`            var conversionAdjustmentUploadService =
                adWordsUser.GetService(Services.V5.ConversionAdjustmentUploadService);

                var response =
                    await conversionAdjustmentUploadService.UploadConversionAdjustmentsAsync(uploadConversionAdjustmentsRequest);`

`var conversionAdjustmentUploadService =
                adWordsUser.GetService(Services.V5.ConversionUploadService);

            try
            {
                var response =
                    await conversionAdjustmentUploadService.UploadClickConversionsAsync(uploadConversionAdjustmentsRequest);`
Questions:                                                                                  Is this a transient error or this APIs are the End of Life?

Google Client Library Version:                                                V6
Sunset Date:                                                                               08/09/2021
Stopped Working Date:                                                            N/A
Challenges:                                                                                 N/A        
Notes:                                                                                          Currently in production and working            
Questions:                                                                                          Until what date can we use this library before it stops working?    

Google Client Library Version:                                                    V7 to V9
Sunset Date:                                                                               V7 – 07/02/2022
Stopped Working Date:                                                            N/A
Challenges:                                                                                 Require compatibility with Microsoft.Abstraction.Configuration and Microsoft.Abstraction.Logging 5.0.0 which are not compatible with .Net Core 3.1. Need to implement Azure Functions V5 (which don’t support Durable Functions)
                                                                
Options:
1.	Rewrite our own integration with the API and therefore avoid using the Google libraries
a.	Cost: Medium to High – will require dev work and a restructure of the layer that does all the authentication and all the other calls to google. Need to add proprietary objects into the code.
b.	Risk: High – Every time an API version is deprecated, then we need to change the models and API calls accordingly. Also need more testing and maintenance.
2.	Convert from durable function to normal function app
a.	Cost: Medium – need to rework the code structure and make sure the retry options are working.
b.	Risk: Low/Medium – in case there are no compatibility issues as we are experiencing now (new frameworks not compatible with each other etc) it requires a bit of rework to accommodate the new libraries. If there are no compatibility issues and there are no breaking changes between the google libraries, then it really takes 5 minutes to update the libraries. 

At the moment our Azure functions are running on windows and using .Net Core 3.1.

Can you please clarify the above questions?

Thanks,
Marco.

**Comment by AnashOommen** [comment]
Hi Marco,

There are multiple issues being covered here, so let's cover them one by one.

1) We generally go by the API version number, and the latest version of the client library supports all the API versions that are available at that time. The deprecation schedule of the API itself is available at https://developers.google.com/google-ads/api/docs/sunset-dates.

So you are using `Services.V5.ConversionAdjustmentUploadService` right now, and API version `v5` is sunset. I'm assuming this is the reason why the API call stopped working all of a sudden. One way to know for sure is to follow the instructions at https://developers.google.com/google-ads/api/docs/client-libs/dotnet/logging and post a request ID from a failed request. I can then look it up to confirm.

2) You should be able to upgrade to the latest API version (`v8`) using client library version (`9.0.0`) without any issues, as long as you upgrade your API code to use `v8` instead of `v5`. The migration guide is available at https://developers.google.com/google-ads/api/docs/version-migration. It is missing `v5`=>`v6` instructions, since `v5` has already sunset. If you need the instructions, I can get you an older version of the page from our revision history.

3) I don't quite follow the compatibility issue you refer about `.NET Core 3.1`. My understanding is that

(a) Any .NET standard implements all its previous standards. E.g. `netstandard2.1` implements `netstandard2.0` and every other standard before it.
(b) .NET Core 3.1 implements `netstandard2.1`.
(c) The client library supports `netstandard2.0` (So does its dependencies, including [`Microsoft.Extensions.Configuration`](https://www.nuget.org/packages/Microsoft.Extensions.Configuration/) and [`Microsoft.Extensions.Logging`](https://www.nuget.org/packages/Microsoft.Extensions.Logging/)). So it should work just fine with a `netcoreapp3.1` application. See the following links:

https://docs.microsoft.com/en-us/dotnet/standard/frameworks#latest-versions
https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support
 
Could you clarify a bit more? Perhaps provide a `netcoreapp3.1` demo project that doesn't compile would be a good starting point to illustrate the issue.

**Comment by MarcoRoberti1995** [comment]
Hi Anash,

I have created a repository here (https://github.com/MarcoRoberti1995/GoogleAdsV8Test) where you can find the test project that doesn't work. 
Essentially the project builds, but the problem is that it doesn't do it correctly as those libraries are not compatible with each other. 

When it builds, the ConfigurationManager.dll is not being loaded correctly, which means that the project throws an exception each time it tries to use it.

If you look in the bin folder, you can see that the ConfigurationManager.dll doesn't exist in the .net standard library output folder, but it only exists in the Azure Function output folder. 

Function output
![image](https://user-images.githubusercontent.com/46632842/127152041-bec5c07d-c083-4f79-b2f6-0a6d1b67babc.png)

Missing in the following Net standard 2.1 project output folder.
![image](https://user-images.githubusercontent.com/46632842/127152133-a2c222dc-e93a-463c-abaa-db345ce112df.png)

We are aware that the 5.0.0 MS libraries aren't compatible with the Azure Functions based on .Net core 3.1 framework , so I think that the compiler might not be able to compile the project correctly and therefore we aren't able to update our libraries.

At the moment we can only use the Google Ads 6.0.0 libraries, which are due to be sunset on the 8th of September and so we need to take action in order to not be caught unprepared.
Unless we rework the project, we won't be able to use the newer versions of the Google Ads untill .NET6 is released, which is scheduled to be released on the 8th November 2021.

With the same project structure, console applications works fine and I think it's related to Azure Functions only.

Any ideas/suggestions on how we can fix this issue? 

Thanks,
Marco.

**Comment by AnashOommen** [comment]
I think the relevant bug is https://github.com/Azure/azure-functions-core-tools/issues/2304. It looks like the issue is that

- Azure functions load the runtime assemblies from its own folder. In my case, this is `C:\Users\anash\AppData\Local\AzureFunctionsTools\Releases\3.28.1\cli_x64\`. 
- As a result, it doesn't copy over the runtime assemblies to `GoogleAdsV8Test\bin\Debug\netcoreapp3.1\bin`.
- This also means that you cannot depend on any library runtime that mismatches with the AzureFunctionTools distribution.
- In this case, the culprit is `System.Configuration.ConfigurationManager`. The Google Ads API library references 5.0.0, whereas Azure references 4.0.3.0. Google Ads API library 6.0.0 referenced 4.7.0, which is why you can work with it. I haven't dug into Azure core tools, but my hypothesis is that Microsoft is doing something with the CLR libraries in a way that is incompatible between netcoreapp3.1 and net50.

I've attached a build of Google.Ads.GoogleAds, 9.0.0 to https://github.com/googleads/google-ads-dotnet/pull/303. This downgrades the dependency on `System.Configuration.ConfigurationManager` to 4.7.0. I can get the demo project to work fine with it. Could you please download the nupkg and confirm if it works fine for your project? If it does, the fix is easy and doesn't have side effects. I can push an updated version during the next scheduled release in August. You can meanwhile use the nupkg I shared to proceed with your migration.

**Comment by MarcoRoberti1995** [comment]
Hi Anash,

we have spent some time trying to use the package you have built for us.

The Google Ads V9 package still depends on version `5.0.0 of Microsoft.Extensions.*` and these packages are not working with functions using .NetCore 3.1.

In our case we are referencing the .Netstandard2.1 libraries that contains the Google Ads Client libraries, which are forcing the package `Microsoft.NET.Sdk.Functions` to use the the 5.0.0 libraries and so when the function tries to run, it throws a runtime error like the following:

![image](https://user-images.githubusercontent.com/46632842/127527679-5cba2ee2-b404-436e-a94a-cdca3c91fc2f.png)

It seems like until Microsoft introduces .net5 for Durable functions, all the reference to `Microsoft.Extensions.*` should be < V 5.0.0 to make it work. 

Is possible to dowgrade those references to be below version 5.0.0 ?

Thanks,
Marco.

**Comment by AnashOommen** [comment]
Hi Marco,

Sorry I missed the part about Durable functions. I've uploaded another snapshot to the PR. Could you give it another try?

Cheers
Anash

**Comment by MarcoRoberti1995** [comment]
Hi Anash,


I confirm that with the latest downgrade of the libraries, I can run the project with your build.
Is it something that you can push to production?

Thanks,
Marco.

**Comment by AnashOommen** [comment]
Hi Marco,

Yes, this is something I can support, I didn't have any other conflicts that I ran into with this downgrade. I am planning the next release for the week of Aug 9th, so is it possible to use this library to proceed with your migration and then upgrade to the latest library version when I push the release in August? You can upgrade to v8 of the API, and your code will continue to work without any changes with the next library upgrade.

**Comment by MarcoRoberti1995** [comment]
Hi Anash,

that will be great and work for us
Thanks a lot!

Marco.

**Comment by MarcoRoberti1995** [comment]
Hi Anash,

just checking if you have any updates on this. When the new version of the client library with downgraded dependencies will be deployed?

Thanks,
Marco.

**Comment by AnashOommen** [comment]
Hi Marco,

If all goes good, I'll release this early next week.

Tx
Anash

**Comment by AnashOommen** [comment]
I've published v10 of the library with the downgraded dependencies, so feel free to update your nuget dependencies.
