### ISSUE TITLE
KeywordIdeaMetrics returning a Month of 13 and no Month of 1

### ISSUE THREAD

**Issue by axtens** [googleads/google-ads-dotnet#407]
dotnet Google.Ads.GoogleAds v12.0.0

A request to return KeywordIdeaMetrics gives erroneous month numbers. 
![KeywordIdeaMetrics oddity](https://user-images.githubusercontent.com/209621/169433862-f1262809-6b0a-431c-8443-cf8019d07f83.png)

Notice that in the pasted graphic, item 8 has a Month of 13 and item 9 a Month of 2.

**Comment by axtens** [comment]
Log generated by
```
TraceUtilities.Configure(TraceUtilities.DETAILED_REQUEST_LOGS_SOURCE,
    "C:\\logs\\details.log", System.Diagnostics.SourceLevels.All);
```
attached
[details.log](https://github.com/googleads/google-ads-dotnet/files/8740766/details.log)

**Comment by AnashOommen** [comment]
@axtens How are you generating this graphic? If you see https://developers.google.com/google-ads/api/reference/rpc/v10/MonthlySearchVolume and https://developers.google.com/google-ads/api/reference/rpc/v10/MonthOfYearEnum.MonthOfYear, then you'd see that the field is an `ENUM` type with two additional fields (`UNSPECIFIED = 0` and `UNKNOWN = 1`). That's why the count runs from 2 to 13 for the other entries (2 being January, 13 being December.

**Comment by axtens** [comment]
Okay, that makes sense. The values I'm receiving are via Newtonsoft's JsonConvert.SerializeObject(). So it's giving me the actual int values of the ENUM rather than the stringified ENUM representation.
