### ISSUE TITLE
Which ads api should I use?

### ISSUE THREAD

**Issue by Zardw** [googleads/google-ads-dotnet#556]
Hello, I want to get these data through API. Even after reading the API documentation, I still don't know which API or APIs to use. Who can help?

![image](https://github.com/googleads/google-ads-dotnet/assets/117419340/29ce92b8-5eda-4271-89d8-6325457f7adc)

**Comment by Raibaz** [comment]
The metrics you are referring to are in the [`Campaign`](https://developers.google.com/google-ads/api/fields/v16/campaign) report.

This being said, if you are having issues that are about the Google Ads API rather than specifically about the client library for .NET, I suggest you refer to the [Support](https://developers.google.com/google-ads/api/support) section of the API devsite.
